#arquivo de configuração para o deployment

apiVersion: apps/v1
kind: Deployment 
metadata:
    name: lembretes-deployment
spec:
    replicas: 1 #quantas replicas queremos
    selector: #especificando rotulos
        matchLabels:
          app: lembretes
    template:
        metadata:
            labels:
                app: lembretes
        spec:
          containers:
            - name: lembretes
            image: rodbossini/lembretes:0.0.1
            resources:
                limits:
                    memory: 256Mi
                    cpu: 1   